/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DemoRoleFaucetInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "certificateNftContract"
      | "requestAdminRole"
      | "requestIssuerRole"
      | "requestRecipientRole"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "certificateNftContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAdminRole",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestIssuerRole",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestRecipientRole",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "certificateNftContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAdminRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestIssuerRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRecipientRole",
    data: BytesLike
  ): Result;
}

export interface DemoRoleFaucet extends BaseContract {
  connect(runner?: ContractRunner | null): DemoRoleFaucet;
  waitForDeployment(): Promise<this>;

  interface: DemoRoleFaucetInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certificateNftContract: TypedContractMethod<[], [string], "view">;

  requestAdminRole: TypedContractMethod<[], [void], "nonpayable">;

  requestIssuerRole: TypedContractMethod<[], [void], "nonpayable">;

  requestRecipientRole: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certificateNftContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestAdminRole"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestIssuerRole"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestRecipientRole"
  ): TypedContractMethod<[], [void], "nonpayable">;

  filters: {};
}
